# Generated by Django 5.1.4 on 2024-12-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('graduate', 'Graduate'), ('intern', 'Intern'), ('doctor', 'Doctor')], default='student', max_length=10),
        ),
    ]
