# Generated by Django 5.1.4 on 2025-01-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Graduate/Trying FMGE', 'Graduate/Trying FMGE'), ('FMGE passed', 'FMGE passed'), ('Working Doctor', 'Working Doctor (With SMC/NMC Registration)'), ('PG Doctor', 'Working PG Doctor (With SMC/NMC Registration)')], default='Student', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('intern', 'Intern'), ('doctor', 'Doctor')], default='student', max_length=10),
        ),
    ]
