# Generated by Django 5.1.4 on 2025-01-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_admin_remarks_alter_user_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('Student', 'Student'), ('Graduate/Trying FMGE', 'Graduate/Trying FMGE'), ('FMGE passed', 'FMGE passed'), ('Working Doctor', 'Working Doctor (With SMC/NMC Registration)'), ('PG Doctor', 'Working PG Doctor (With SMC/NMC Registration)')], default='Student', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='willing_to_be_donor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
