# Generated by Django 5.1.4 on 2025-01-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_category_alter_user_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='hyper_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
