# Generated by Django 5.1.4 on 2025-01-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_announcement_options_announcement_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state_nmc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
