# Generated by Django 5.1.4 on 2025-01-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_user_state_nmc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state_nmc',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
