# Generated by Django 5.1.4 on 2025-01-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_blood_group_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='application',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('Student', 'Student'), ('Graduate/Trying FMGE', 'Graduate/Trying FMGE'), ('FMGE passed', 'FMGE passed'), ('Working Doctor', 'Working Doctor'), ('PG Doctor', 'PG Doctor')], default='Student', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='country_university',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_time_of_payment',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='educational_status',
            field=models.CharField(choices=[('Student (@Abroad University)', 'Student (@Abroad University)'), ('Graduated / FMGE Aspirant', 'Graduated / FMGE Aspirant'), ('FMGE Passed Candidate', 'FMGE Passed Candidate'), ('Internship', 'Internship'), ('Working Doctor', 'Working Doctor'), ('Post Graduation ongoing', 'Post Graduation ongoing'), ('Post Graduation Completed, Working', 'Post Graduation Completed, Working')], default='Student (@Abroad University)', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_qualification',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='payment_transaction_proof',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state_nmc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='university_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='willing_to_be_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_completion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_joining',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
