# Generated by Django 5.1.4 on 2025-01-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_agreement_user_application_user_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year_of_completion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_of_joining',
            field=models.CharField(max_length=100),
        ),
    ]
