# Generated by Django 5.1.4 on 2025-01-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_announcement_hyper_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
