# Generated by Django 5.1.4 on 2025-01-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_announcement_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date_time']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
