# Generated by Django 5.1.4 on 2025-02-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_user_state_nmc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='medical_qualification',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_transaction_proof',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='state_nmc',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
