# Generated by Django 5.1.4 on 2025-02-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_user_medical_qualification_alter_user_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='aid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='cid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
