# Generated by Django 4.2.19 on 2026-02-16 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_announcement_visibility_rulebook_galleryimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('text', 'Short Answer (Text)'), ('textarea', 'Long Answer (Textarea)'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox'), ('number', 'Number'), ('email', 'Email'), ('tel', 'Phone Number')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Order in which question appears (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Only active questions appear in registration form')),
                ('options', models.TextField(blank=True, help_text="For dropdown/radio/checkbox: comma-separated options (e.g., 'Option1,Option2,Option3')", null=True)),
                ('help_text', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_date', models.DateField(blank=True, null=True)),
                ('answer_number', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('answer_boolean', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registrationquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['question__order', 'created_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
