# Generated by Django 4.2.19 on 2026-02-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_registrationquestion_registrationanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationanswer',
            name='answer_file',
            field=models.CharField(blank=True, help_text='MinIO file path for file uploads', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registrationquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Short Answer (Text)'), ('textarea', 'Long Answer (Textarea)'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox'), ('number', 'Number'), ('email', 'Email'), ('tel', 'Phone Number'), ('file', 'File Upload (PDF/JPG)')], default='text', max_length=20),
        ),
    ]
